name: Build and Publish APK

on:
  push:
    branches: [ "Max" ]
   
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust the Java version as needed

      - name: Build APK Release
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload APK to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.TKT }}
        run: |
          apkPath="app/build/outputs/apk/release/app-release.apk"
          tagName="v${{ github.run_number }}"
          releaseTitle="New Build - ${tagName}"

          # Create a release
          uploadUrl=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\":\"$tagName\",\"name\":\"$releaseTitle\",\"draft\":false,\"prerelease\":false}" | jq -r '.upload_url')

          # Upload APK file
          curl -s -X POST \
            -H "Authorization: token $TKT" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary @$apkPath \
            "$uploadUrl?name=$(basename $apkPath)"
