name: Android Build and Release

on:
  push:
    branches:
      - Max
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Download uber-apk-signer
        run: wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar

      - name: Sign and Align APK
        env:
          KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          java -jar uber-apk-signer-1.3.0.jar \
            --apks app/build/outputs/apk/release/app-release-unsigned.apk \
            --ks $KEYSTORE_PATH \
            --ksAlias $KEY_ALIAS \
            --ksPass $KEYSTORE_PASSWORD \
            --ksKeyPass $KEY_PASSWORD \
            --out app/build/outputs/apk/release/ \
            --allowResign \
            --verbose

      - name: Verify APK file existence
        run: ls -l app/build/outputs/apk/release/

      - name: Send APK to Telegram
        env:
          TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@app/build/outputs/apk/release/app-release-aligned-signed.apk https://api.telegram.org/${TELEGRAM_BOT_ID}:${TELEGRAM_BOT_TOKEN}/sendDocument
